### ISSUE TITLE
Shadow

### ISSUE THREAD

**Issue by AnbalaganD** [SudarvizhiSelvam/XamarinProjects#1]
@SudarvizhiSelvam explain how to add drop shadow in xamarin android

**Comment by SudarvizhiSelvam** [comment]
theriyala nan xamarin  marathutan ios dhan therium

**Comment by AnbalaganD** [comment]
@SudarvizhiSelvam Thanks for quick reply ;)

**Comment by AnbalaganD** [comment]
If you want drop shadow we can achieve.
1) use Frame
2) Custom Renderer
3) 9-Patch Image


I used second one its work perfect for me as I expected.
