### ISSUE TITLE
iOS Notification not appearing in the notification tray when app is killed

### ISSUE THREAD

**Issue by AnbalaganD** [SudarvizhiSelvam/XamarinProjects#3]
Hi ,

iOS notification work fine if app run in foreground but problem is iOS notification Not appearing when app run on background or kill.

**Comment by SudarvizhiSelvam** [comment]
notifaction will not work when it is killed oru key vachikanum active ila
nu notufaction center vachi panalam

**Comment by AnbalaganD** [comment]
okey.
